# Generated by Django 2.1.3 on 2018-12-21 08:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='LeaveMessage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.CharField(max_length=100)),
                ('message', models.TextField(max_length=256)),
                ('create_date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AddField(
            model_name='usertable',
            name='user_id',
            field=models.CharField(default=models.TextField(max_length=10), max_length=100),
        ),
        migrations.AlterField(
            model_name='usertable',
            name='update_date',
            field=models.DateTimeField(default=' '),
        ),
    ]
