# Generated by Django 2.1.3 on 2018-12-22 17:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_auto_20181221_1538'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usertable',
            name='user_id',
            field=models.CharField(default=models.CharField(max_length=100), max_length=100),
        ),
        migrations.AlterField(
            model_name='usertable',
            name='username',
            field=models.CharField(max_length=100),
        ),
    ]
