# Generated by Django 2.1.3 on 2018-12-22 18:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_auto_20181222_1749'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('account', models.CharField(max_length=200)),
                ('name', models.CharField(max_length=200)),
                ('password', models.CharField(max_length=200)),
                ('sex', models.CharField(choices=[('1', '男'), ('2', '女')], default='', max_length=25)),
                ('email', models.EmailField(max_length=200)),
                ('phone', models.CharField(max_length=55)),
                ('creDate', models.DateTimeField(auto_now_add=True)),
                ('lastLogin', models.DateTimeField(auto_now=True)),
                ('enable', models.IntegerField(default=1)),
            ],
            options={
                'verbose_name': '用户',
                'verbose_name_plural': '用户',
                'db_table': 'User',
            },
        ),
        migrations.DeleteModel(
            name='UserTable',
        ),
    ]
